runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://intersect:4wabbit4@ds033015.mlab.com:33015/hotornot
  APP_ID: utXysazDczvny5sBUme5HZIzfUrybjppWIc8aVGb
  MASTER_KEY: 1o6z9ePR3qPnRU0jHIP4iWToNzkANKIr3UNHwelq
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  