branch-defaults:
  master:
    environment: parseserver-2qqi8-env-test
  test:
    environment: hotornot-test-dev
global:
  application_name: hotornot-test
  default_ec2_keyname: intersect_key
  default_platform: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
